name: synth
description: Creds Synth components for flutter.
version: 0.0.1
homepage: https://github.com/data-charya/Synth-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.shanwill.synth
        pluginClass: Synth
      ios:
        pluginClass: Synth
      macos:
        pluginClass: Synth
      # web:
      #   pluginClass: Synth
      #   fileName: hello_web.dart

  assets:
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
          weight: 400
        - asset: fonts/Gilroy-Bold.ttf
          weight: 900
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
  
